name: magicepaperapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: '3.38.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.5+1
  # nfc_manager: ^3.5.0
  flutter_nfc_kit: ^3.6.0
  convert: ^3.1.2
  flutter_svg_provider: ^1.0.7
  matrix2d: ^1.0.4
  image: ^4.7.1
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  app_settings: ^7.0.0
  fluttertoast: ^9.0.0
  pro_image_editor: ^11.15.1
  gal: ^2.3.1
  file_saver: ^0.3.1
  bot_toast: ^4.1.3
  media_kit: ^1.2.6
  url_launcher: ^6.3.1
  google_fonts: ^6.3.3
  file_picker: ^10.3.8
  flutter_colorpicker: ^1.1.0
  mime: ^2.0.0
  mobile_scanner: ^7.1.4
  barcode_widget: ^2.0.4
  intl: ^0.20.2
  path_provider: ^2.0.15
  get_it: ^9.2.0
  path: ^1.9.1
  permission_handler: ^12.0.1
  ndef: ^0.4.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/displays/
    - assets/canvas/
    - assets/icons/
